name: Potent Shouts
favicon: null
layout_spectrum: 0.9208771688863635
typography_spectrum: 0.2705326157156378
title: Potent Shouts Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5248501936439425
  lightness: 0.5006569803226739
  saturation: 0.6357651753351092
  rhythmicContrast: 0.3354182012844831
purpose: []
